language: node_js
node_js:
  - "12"
services:
  - docker

before_install:

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f ./docker/Dockerfile.multistage -t lemontree2000/stacksweet.com:latest .
  - docker push lemontree2000/stacksweet.com:latest